HACKING.md, Makefile, test/vm.install, test/vm.install-sub-man
The test suite already uses `TEST_SCENARIO` to specify which branch of
subscription-manager checkout & test, defaulting to "main". While this
works nicely, it unconditionally tests subscription-manager from
upstream sources.
Introduce a new special value for `TEST_SCENARIO`, i.e. "system": this
does not represent any special branch, but simply avoids installing
subscription-manager from sources, and relies on it being already
installed in the test image. Document the existing behaviour of
`TEST_SCENARIO`, and this new addition, in our `HACKING` file.
The actual implementation is simple: all is needed for a "system"
scenario is to not pass to image-customize the tarballs & scripts of
subscription-manager.
=> tests: allow TEST_SCENARIO=system

HACKING.md, Makefile, package.json, subscription-manager-cockpit.spec.tmpl
A number of some very small changes, too small to be sent in their own PRs:
- spec: fix license to LGPLv2
- HACKING: fix project reference
- tests: switch default TEST_OS to centos-9-stream
- Remove one more vagrant leftover
- Fix reference to the repository
- tests: bump image-customize RAM to 2048
=> Some minor changes

webpack.config.js
By default, webpack does not clean up dist/, so when you e.g. touch the
code and rebuild with `NODE_ENV=devel`, the old compressed assets from
a previous `production` build were left in place, and cockpit could
serve the old wrong ones. Enable the `clean` output option to fix this [1].
Also force the rewrite of all files with `compareBeforeEmit: false`, so
that the time stamps actually get updated on a webpack run. This fixes
`make` rules and unnecessary rebuilds when nothing changed.
Fixes starter-kit#563
[1] https://webpack.js.org/configuration/output/#outputclean
Cherry-picked from starter-kit commit 3aff8acad1b198cb
=> webpack: Always regenerate and clean up dist/

test/check-subscriptions, test/files/mock-insights
Few improvements for the test bits that should not cause any behaviour change:
- pass arguments to `Machine.execute()` when possible, to avoid doing shell escaping manually
- `machine_python()` is simplified a bit
- run `restorecon` in `setUp()` to fix the SELinux contexts of what is created/uploaded there
- minor changes to `mock-insights` wrt its Python stuff or its logging
=> tests: small changes

.flake8, .github/workflows/stylish.yml, pyproject.toml, test/check-subscriptions, test/files/mock-insights
This PR improves what was introduced with #6:
- format the Python sources that do not end with `.py` using black (same version used currently for sub-man), and make sure black now handles them
- add one more flake8 exclusion forgotten earlier
- include more files for flake8
- add a simple workflow using GitHub Actions that runs black & flake8
- in case of flake8 failure, the errors are showed inline in the sources (thanks to a nice action)
=> Reformat with black, enforce black & flake8 with GHA

Makefile
Disable the printing of the echo commands that write the filename of the
VM image for tests in the `vm` and `print-vm` targets.
This makes it possible to use their outputs, especially the 'print-vm'
target.
Backport from https://github.com/cockpit-project/starter-kit:
- PR: https://github.com/cockpit-project/starter-kit/pull/568
- commit https://github.com/cockpit-project/starter-kit/commit/0ece83483d4a33ba58d93f9641711a18c5543f8b
=> `Makefile`: avoid spurious echo

subscription-manager-cockpit.spec.tmpl
Group is no more needed on Red Hat distros for some years already:
https://fedoraproject.org/wiki/Changes/Remove_Group_Tag
=> spec: limit Group to SUSE distros

subscription-manager-cockpit.spec.tmpl
Backport from https://github.com/cockpit-project/starter-kit some commits that make the packaging more in line with the Fedora guidelines; in addition, add more changes resulting from the Fedora review:
https://bugzilla.redhat.com/show_bug.cgi?id=2081432
- https://github.com/cockpit-project/starter-kit/pull/573
- https://github.com/cockpit-project/starter-kit/commit/b47bb4714ac8a77459a4656012fae2308b857670
- https://github.com/cockpit-project/starter-kit/commit/0c954dbf499d93511d0988601bc00f442ab198b2
- https://github.com/cockpit-project/starter-kit/commit/bee838088d09bc6d73b87e19b26df188266bfc6d
- https://github.com/cockpit-project/starter-kit/commit/f86c02c60ebb3e87d5ecf62ed0456b20a6d983f4
- removing the references to fmf, since it is not used here
- …
=> Fedora packaging fixes

src/subscriptions-client.js
Reword the text of some untranslated error messages to be more
"elegant", for example with the proper spelling of "IPv6" & "URL",
and by removing the ellipsis (which fit "in progress" messages).
Also, use the gettext function to properly translate them, and make sure to use a proper error handling based on JS promises (like already used) rather than throwing raw messages (which cockpit display only as "Ooops" window).
This fixes the cockpit parts of
https://bugzilla.redhat.com/show_bug.cgi?id=2076914
Card ID: ENT-4943
=> Translate few error messages

subscription-manager-cockpit.spec.tmpl
The Cockpit Web Service (cockpit-ws) is not required to use the
subscription-manager plugin, and it is something the user chooses to
install directly or indirectly, affecting the entirety of Cockpit.
Hence, drop its Recommends.
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2093840
Card ID: ENT-5084
=> 2093840: spec: drop cockpit-ws

src/subscriptions-view.jsx
Even after commit cd1b5f97916a3e883ae301ea6e8f3318a8654b48 and
commit 5f0b03d879c9619eec01d85a8741f762af26f2ce, the situation of the
main curtain view still remained a bit flaky: in particular, if the
configuration was loaded before the subscription status, there would be
a (brief) flash of the view "couldn't get system subscription status".
There is a bit of duplicated logic for loaded & status in `render()` and
`renderCurtains()`, plus the logic did not even consider all the cases
correctly, so let's try to reorganize & simplify this a bit.
In particular:
- split the creation of a "loading view" and an "error view" in own
function: this will make it easier to call the right one when needed
- move all the checks for the status (excluding the ones needed for the
actual error to show in …
=> 2023430: fix/simplify the loading/error view checks

subscription-manager-cockpit.spec.tmpl
The Cockpit plugin can register the system to Red Hat Insights using
`insights-client` (which can be installed if missing); hence it makes
sense to add some package relationship for it.
Considering that `insights-client` exists only on RHEL, limit the
insights-client relationship to RHEL only.
Also, `insights-client` is in the AppStream repository, while the Cockpit
plugin is in BaseOS; because of that, there cannot be neither an hard
`Requires` nor a `Recommends`, hence the only way is a `Suggests`.
=> spec: suggest insights-client on RHEL

Makefile
In particular this improves the run-tests scheduler to work better on
our current infrastructure:
https://github.com/cockpit-project/cockpit/commit/49a7122df2
---
sub-man tests currently fail a *lot* [like this](https://cockpit-logs.us-east-1.linodeobjects.com/pull-3640-20220725-091346-535ac172-rhel-8-6-candlepin-subscription-manager-subscription-manager-1.28/log.html). This also needs to be applied to the umpteen older branches, I'll send that once this lands.
=> Bump cockpit test API to 273 + run-tests scheduler fix

src/index.js
This way cockpit translates the static elements of the base HTML page of the module, including the page title. This follows what is generally done by other cockpit modules.
Thanks to Martin Pitt for the hint!
=> 2077759: invoke cockpit.translate() after document loading

src/subscriptions-register.jsx
* Setting this attribte should disable suggestions of creating new secure password. Unfortunatelly some web browsers still ignores this attribute.
=> Set autocomplete to "current-password" for password inputs

Makefile, src/subscriptions-client.js
That API was deprecated years ago. Use the standard Promise API and
promise chaining instead.
Also clean up some weird then/catch/then chains.
---
Still draft, as there is one usage left which I don't understand:
```
client.getSyspurposeStatus = () => {    
let dfd = cockpit.defer();    
if (isRegistering) { return dfd.promise(); }    
```
This *never* gets resolved or referenced anywhere else. I'm reasonably sure this just meant to say `return Promise.resolve()`, i.e. return a resolved promise instead of leaving the caller hanging in the air forever. But I want to run tests first.
**Update**: Pushed an additional commit to fix that.
=> Drop usage of obsolete cockpit.defer()

subscription-manager-cockpit.spec.tmpl
Since on SUSE distributions there is a different format, leave the previous format for them.
=> spec: convert License to SPDX

src/subscriptions-client.js, src/subscriptions-view.jsx
done/fail/always is the long-obsolete `cockpit.defer()` jQuery promise API, which will be dropped eventually. Replace them with the standard `Promise` API.
This requires a little teak in safeDBusCall() -- while `.fail()` also returns the rejection, `Promise.catch()` handles it and returns nothing.
In `InstalledProducts.handleAutoAttach()`, both handlers in were doing exactly the same thing, so use finally() instead. Also use an arrow instead of a function to avoid the `self = this` dance.
=> Fix obsolete cockpit defer API

test/check-subscriptions, test/files/mock-insights
Fix the tests, and in particular `testSubAndInAndFail`, to ensure they work properly in all the cases, and also with newer versions of `insights-core`:
- extend the timeouts for certain registration, unregistration, and Insights operations
- fix `mock-insights` to properly error out when querying for an unregistered system
- use a different method to break `insights-client` according to newer changes in `insights-core`
See the messages of the various commits for much longer descriptions of the reasons & changes.
=> tests: fix Insights test, increase certain timeouts

test/check-subscriptions
The data collection done by insights-client takes more and more time, and it may take even more in case the test system (running as VM) is running inside another VM.
Hence, extend a bit more the timeout needed while waiting for the registration to Insights.
Extends/updates commit c006e1ed6f29f56691f2f31f225246d1e8311864.
=> test: wait more when registering to Insights

.github/workflows/stylish.yml
=> chore: bump version of black to 24.3.0

test/check-subscriptions
subscription-manager has a unified "syspurpose" command to set the various syspurpose bits; since the top-level commands will be deprecated and removed soon, switch to the unified command.
=> chore: test: use the new syspurpose command

src/index.js, src/subscriptions-client.js, src/subscriptions-register.jsx, src/subscriptions-view.jsx, test/check-subscriptions
* Card ID: CCT-425
* Removed "Auto-Attach" button, because corresponding D-Bus method was removed from rhsm.service due to SCA only effort
* Renamed "Auto-attach" option from registration dialog to "Enable content"
* Modified integration tests
=> fix: Remove Auto-attach button

test/files/mock-insights
Improve a bit the `mock-insights` fake service to improve certain bits, and implement new APIs. In particular:
- fix the handling of the helper `systems` dictionary to index by the own Inventory ID (i.e. the current hardcoded one)
- implement more endpoints needed to support the non-legacy-upload mode of `insights-client`
See the messages of each commit for longer explanations.
=> mock-insights: various changes/improvements

src/insights.jsx
The file `/etc/insights-client/.last-upload.results` is watched to determine when was the last upload done. A couple of important notes about it:
1) even though it is read (and parsed), its content is actually never used currently
2) the file is written by insights-client (better: insights-core) only when `legacy_upload` is true (which is the default as of this writing)
While (1) is not much an issue, (2) means that the displaying of the last upload (timestamp) to Insights is not available when switching insights-client to non-legacy-upload.
To avoid both the issues, switch from `.last-upload.results` to `/etc/insights-client/.lastupload`:
- `.lastupload` is always written, no matter the mode, and its modification timestamp is indeed accurate
- stop reading the file at all, saving a bit …
=> feat: switch from .last-upload.results to .lastupload

.flake8
Explicitly ignore the locally downloaded nodejs modules when running flake8 (as flake8 does not use `.gitignore`); this way it is possible to run flake8 while developing and running tests.
=> chore: ignore node_modules for flake8

test/check-subscriptions, test/files/mock-insights
Switch the authentication method of insights-client to CERT-based, which uses the consumer certificate & key of subscription-manager.
This means using mTLS for authentication, still without verifying them, just like the previous fake credentials; this is still acceptable in the testing environment of a transient guest.
=> test: switch to CERT auth for insights-client

test/files/mock-insights
`ssl.wrap_socket()` is long deprecated, and dropped in Python 3.12. Switch to use an `SSLContext` for client authentication. Load also the system CA store, as it contains the Candlepin CA: this way, the CERT-based authentication (using the consumer certificate generated by Candlepin) can be validated.
=> test: mock-insights: switch away from ssl.wrap_socket()

test/check-subscriptions
Ensure that subscription-manager is configured so that the package manager can properly receive content from the repositories of the self-deployed Candlepin. This should have been done in the past, and it will be critical for switching to SCA for testing: in SCA mode, all the content of the organization is available by default, and some repositories are also automatically enabled.
This means:
- installing the GPG key for RPM packages
- setting the baseurl in rhsm.conf
-------
This PR requires an updated `services` cockpit image after https://github.com/cockpit-project/bots/pull/6708 is merged.
=> test: setup the subscription repositories

test/check-subscriptions
Use "donaldduck" as organization to really register using SCA.
Followup of commit 16caea1552fcede7a7318a60153c46bfe94fe650.
=> test: switch one more org to SCA one

Makefile, test/check-subscriptions
This requires a couple of adaptations in the actual test script:
- make use of the `pywrap` script available in cockpit's `test/common` to import all the right modules for us (removing the manual imports)
- tweak the import of `testvm` to be done like done in cockpit tests
There should be no behaviour changes.
=> Update cockpit test lib to 323

Makefile
In particular, this pulls in
https://github.com/cockpit-project/cockpit/commit/7957a125baa to avoid test failures with cockpit ≥ 326.
---
This broke the most recent CentOS 10 refresh in https://github.com/cockpit-project/bots/pull/7030
=> Bump cockpit testlib to 327

src/insights.jsx
cockpit.{resolve,reject} have been deprecated for years. Use the standard JS promise API.
=> fix: Drop deprecated cockpit.resolve()

Makefile, test/run
Starting from cockpit 286 they have a `.js` extension, so adapt the message extraction rules for them.
Also run the message extraction during the tests, so this kind of 
problems can be detected automatically.
=> Makefile: fix names of po extractor tools

test/check-subscriptions
Various changes for the test scripts, with no actual behaviour changes:
- use existing APIs from the cockpit testlib (`testOnly()`, `Machine.write()`)
- use `/etc/pki/product-default` for product certificates
- use a simpler way to wait for Candlepin
- drop the no more needed activation key Python script
- switch usages of `%` string interpolation with f-strings
=> test: various misc changes

src/index.html
Since 2019(!) translatable is deprecated up by our `html2po.js` script and replaced by `translate` or `translate="yes"`.
=> Stop using deprecated translatable for html

src/subscriptions-view.jsx
* Card ID: CCT-548
Refactored the installed products list for SCA mode, hiding non-relevant details (e.g. Status, Starts, Ends). Also removed "Unknown status" from the header of installed products.
=> refactor: Simplify displaying of installed products

src/subscriptions-view.jsx
* Card ID: CCT-549
To be consistent with subscription-manager CLI tool, when system is registered in SCA mode, the status now shows "Registered" instead of "Disabled". The label for "Subscription status" is also renamed to "Status".
=> refactor: Display status consistent with subscription-manager CLI tool

src/subscriptions-view.jsx
* Card ID: CCT-550
Since system purpose is not applicable, the system purpose status is now hidden. The system purpose panel now only displays service level, usage, role, and addons when applicable.
=> refactor: Remove system purpose status

test/vm.install-sub-man
Newer versions of Fedora implement:
https://fedoraproject.org/wiki/Changes/Unify_bin_and_sbin
Because of that, now the "subscription-manager" executable is installed
in `/usr/bin`, and the old usermode symlink is gone. To properly handle 
those changes, then:
- remove all the "subscription-manager" executables before installing 
subscription-manager from the wanted sources
- use "-n" when moving the "subscription-manager" executable to not
error out in case the "sbin" install location is set to be "bin"
=> build: fix installation of sub-man with newer Fedora

src/index.js, src/insights.jsx, src/subscriptions-view.jsx, test/check-subscriptions
This improves the managing of state between webui and subscriptionsClient. There is a new `addAlert` handler function which manages alerts and fixes bug where an already present alert was rendered on each new render.
Also fixes createRoot() calling and the following error:
```
Warning: You are calling ReactDOMClient.createRoot() on a container that
has already been passed to createRoot() before. Instead,
call root.render() on the existing root instead if you want to update it.
```
=> Various fixes in state management

src/insights.jsx, test/check-subscriptions
This PR was previously #100 and I cherry-picked commit from #97 so there is no need for 2 QE verifications.
---
#100 
* Card ID: CCT-1511
* I removed links to console.redhat.com as there is no guarantee of the system registering to console.redhat.com with the introduction of Insights on-prem.
---
#97 
* Card ID: CCT-1082
* Card ID: CCT-1421
* We decided to remove reading of /var/lib/insights/insights-details.json file, because insights-client will stop generating this file completly in the future.
* The link on details will remain
* Fixed integration tests
=> feat(subman): remove link to console.redhat.com AND fix: Do not use insights-details.json
